### ISSUE TITLE
this error on console

### ISSUE THREAD

**Issue by gsgoldma** [KohakuBlueleaf/a1111-sd-webui-haku-img#13]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\extensions\a1111-sd-webui-haku-img\hakuimg\sketch.py", line 38, in run
    return xdog(*args)
  File "D:\stable-diffusion-webui\extensions\a1111-sd-webui-haku-img\hakuimg\sketch.py", line 24, in xdog
    dog = dog_filter(img, kernel, sigma, k_sigma, gamma)
  File "D:\stable-diffusion-webui\extensions\a1111-sd-webui-haku-img\hakuimg\sketch.py", line 15, in dog_filter
    g1 = gaussian(img, kernel, sigma)
  File "D:\stable-diffusion-webui\extensions\a1111-sd-webui-haku-img\hakuimg\sketch.py", line 11, in gaussian
    return cv2.GaussianBlur(img, (kernel, kernel), sigma)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\smooth.dispatch.cpp:294: error: (-215:Assertion failed) ksize.width > 0 && ksize.width % 2 == 1 && ksize.height > 0 && ksize.height % 2 == 1 in function 'cv::createGaussianKernels'

**Comment by KohakuBlueleaf** [comment]
kernel size should be 0 or odd number.
