### ISSUE TITLE
"Other" tab: some errors

### ISSUE THREAD

**Issue by IPv6** [KohakuBlueleaf/a1111-sd-webui-haku-img#16]
Sometimes when changing image size with fill left/right there python error in console

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/stable-diffusion-webui/extensions/a1111-sd-webui-haku-img/inoutpaint/main.py", line 20, in run
    new_img, mask = resize_with_mask(
  File "/content/stable-diffusion-webui/extensions/a1111-sd-webui-haku-img/inoutpaint/utils.py", line 15, in resize_with_mask
    new_img = Image.new('RGB', (w+l+r, h+u+d))
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

If i change values a bit - error gone

Thanks for useful tool!

**Comment by IPv6** [comment]
Sometimes "send to extras"/"send to impaint" not working for fisrt time. Tab switches, canvas size in inpaint/etc tabs updating itself, but there is white rectangle instead of image from Haiku. After 2-3 attempts to "send to extras"/"send to impaint" - it finally sends real image

**Comment by KohakuBlueleaf** [comment]
I try to reproduce the problem but seems like it is gone.
If this problem still exist, open a new issue.
