### ISSUE TITLE
Error after installing & restart WebUI

### ISSUE THREAD

**Issue by JekkaBoi** [KohakuBlueleaf/a1111-sd-webui-haku-img#2]
Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-haku-img/scripts/main.py", line 24, in <module>
    all_btns: list[tuple[gr.Button, ...]] = []
TypeError: 'type' object is not subscriptable

Help .-., I'm using TheLastBen WebUI & didn't know what caused it. It happened after the extension was installed and tried to restart the WebUI.

Thank you!

**Comment by KohakuBlueleaf** [comment]
What is your python version?
This grammer can only run in python>=3.10

**Comment by JekkaBoi** [comment]
Oh noo .-.

I'm using TheLastBen Google Colab version (https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb), and it's used 3.8.10 version

**Comment by KohakuBlueleaf** [comment]
I can fix this problem but I may use some other py3.1x grammar so I may not try to "fix" them(
Sorry!

**Comment by JekkaBoi** [comment]
I see, no problem. Will try to upgrade the pyhton ^^. Thank you so much!
