### ISSUE TITLE
Error after SD gradio update

### ISSUE THREAD

**Issue by SuperMaoUwU** [KohakuBlueleaf/a1111-sd-webui-haku-img#37]
As title says i remember reading that SD upgraded gradio and im getting this error after updating

"
add tab
*** Error executing callback ui_tabs_callback for C:\Users\Anton\Downloads\stable-diffusion-webui-forge\extensions\a1111-sd-webui-haku-img\scripts\main.py
    Traceback (most recent call last):
      File "C:\Users\Anton\Downloads\stable-diffusion-webui-forge\modules\script_callbacks.py", line 283, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\Anton\Downloads\stable-diffusion-webui-forge\extensions\a1111-sd-webui-haku-img\scripts\main.py", line 456, in add_tab
        _release_if_possible(
      File "C:\Users\Anton\Downloads\stable-diffusion-webui-forge\extensions\a1111-sd-webui-haku-img\scripts\main.py", line 635, in _release_if_possible
        if isinstance(component, gr.events.Releaseable):
    AttributeError: module 'gradio.events' has no attribute 'Releaseable'

---
"
is there anything i can do to make it work again?

**Comment by KohakuBlueleaf** [comment]
Thx for notice
I will take a look once I have free time
should be fixed in August but not recent

**Comment by EveKaczmarek** [comment]
Hi, 

Any update on this matter?
