### ISSUE TITLE
getting error in blend mode after auto update

### ISSUE THREAD

**Issue by gsgoldma** [KohakuBlueleaf/a1111-sd-webui-haku-img#7]
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\stable-diffusion-webui\extensions\a1111-sd-webui-haku-img\hakuimg\blend.py", line 98, in blend
    for alpha, mask_blur, mask_str, mode, img in reversed(zip(*chunks)):
TypeError: 'zip' object is not reversible

maybe its unrelated, not sure. the preview window to the right gets an error box and shows no images

**Comment by KohakuBlueleaf** [comment]
@gsgoldma update again, I already fixed this error
